version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: brethren
      POSTGRES_PASSWORD: brethren
      POSTGRES_DB: brethren
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    environment:
      PORT: 4000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: brethren
      DB_PASSWORD: brethren
      DB_NAME: brethren
      JWT_SECRET: super-secret
    depends_on:
      - postgres
    ports:
      - '4000:4000'

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '4200:80'

volumes:
  postgres_data:
